{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "book-server-helm.fullname" . }}
  labels:
    {{- include "book-server-helm.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "book-server-helm.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
